version: 2
jobs:
  build:
    TZ: /usr/share/zoneinfo/Asia/Tokyo
    docker:
      - image: circleci/python
    working_directory: ~/rails-docker-base
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: ssh -o StrictHostKeyChecking=no -v $SSH_USER@$SSH_HOST "touch test.txt"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
